---
- name: Download helm3
  get_url:
    url: https://get.helm.sh/helm-v3.3.1-linux-amd64.tar.gz
    dest: /tmp
    mode: '0740'

- name: Download etcdctl
  get_url:
    url: https://github.com/etcd-io/etcd/releases/download/v3.4.13/etcd-v3.4.13-linux-amd64.tar.gz
    dest: /tmp
    mode: '0740'

- name: Download Octant
  get_url:
    url: https://github.com/vmware-tanzu/octant/releases/download/v0.15.0/octant_0.15.0_Linux-64bit.tar.gz
    dest: /tmp
    mode: '0740'