---
- name: download helm3
  get_url:
    url: "https://get.helm.sh/helm-v{{ helm.version }}-linux-amd64.tar.gz"
    dest: /tmp
    mode: '0740'
  when: "{{ helm.enabled }} == true"

- name: download etcdctl
  get_url:
    url: https://github.com/etcd-io/etcd/releases/download/v3.4.13/etcd-v3.4.13-linux-amd64.tar.gz
    dest: /tmp
    mode: '0740'

- name: download Octant
  get_url:
    url: https://github.com/vmware-tanzu/octant/releases/download/v0.15.0/octant_0.15.0_Linux-64bit.tar.gz
    dest: /tmp
    mode: '0740'

- name: download fluxctl
  get_url:
    url: https://github.com/fluxcd/flux/releases/download/1.20.2/fluxctl_linux_amd64
    dest: /tmp
    mode: '0755'