---
- name: Extract helm3 libraries
  unarchive:
    src: "/tmp/helm-v{{ hel.version }}-linux-amd64.tar.gz"
    dest: /tmp
  when: "{{ helm.enabled }} == true"

- name: Extract etcdctl
  unarchive:
    src: /tmp/etcd-v3.4.13-linux-amd64.tar.gz
    dest: /tmp

- name: Extract Octant
  unarchive:
    src: /tmp/octant_0.15.0_Linux-64bit.tar.gz
    dest: /tmp