---
- name: install helm3
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/bin
    owner: ec2-user
    group: ec2-user
    mode: '0744'

- name: install etcdctl
  copy:
    src: /tmp/etcd-v3.4.13-linux-amd64/etcdctl
    dest: /usr/bin
    owner: ec2-user
    group: ec2-user
    mode: '0744'

- name: install octant
  copy:
    src: /tmp/octant_0.15.0_Linux-64bit/octant
    dest: /usr/bin
    owner: root
    group: root
    mode: '0744'

- name: setting up octant service
  copy:
    src: "{{ role_path }}/files/octant.service"
    dest: /usr/lib/systemd/system/
    owner: root
    group: root
    mode: '0755'

- name: enable service octannt and ensure it is not masked
  systemd:
    name: octant
    enabled: yes
    masked: no

- name: make sure octant service is running
  systemd:
    state: started
    name: octant

- name: install fluxctl
  copy: 
    src: /tmp/fluxctl_linux_amd64
    dest: /usr/bin/fluxctl
    owner: ec2-user
    group: ec2-user
    mode: '0755'